export const STUDIO_COPY = {
  zh: {
    tryLuck: "试试手气",
    tryLuckAria: "随机打开一个 Skill",
    creations: "生成记录",
    skills: "Skills",
    settings: "设置",
    appearance: "外观",
    themeLight: "浅色",
    themeDark: "深色",
    language: "语言",
    languageSystem: "系统",
    languageChinese: "中文",
    languageEnglish: "English",
    openFullscreen: "打开全屏",
    registerSkill: "注册 Skill",
    refreshSkills: "刷新 Skill",
    skillPath: "Skill 绝对路径",
    skillPathPlaceholder: "Skill 目录或 SKILL.md 的绝对路径",
    overwriteRegistered: "覆盖已注册",
    registering: "校验中…",
    registerToStudio: "注册到 Studio",
    fillSkillPath: "请填写 Skill 目录或 SKILL.md 的绝对路径。",
    registered: (name) => `已注册 ${name}。`,
    installed: (destination) => `已安装到 ${destination || "~/.codex/skills"}。`,
    backToFeed: "返回 Feed",
    skillContent: "Skill 内容",
    myGenerations: "我的生成",
    installToCodex: "安装到 Codex",
    overwriteInstall: "覆盖安装",
    generateSame: "生成同款",
    prompt: "提示词",
    promptPlaceholder: "描述你想看见的画面…",
    addReference: "添加参考图",
    referenceImage: "参考图",
    removeReference: "移除参考图",
    writeAScene: "写下想生成的画面",
    handOff: "交给 Codex",
    handingOff: "正在交出…",
    composerReady: "可以开始",
    composerHandedOff: "已交给 Codex",
    composerOpenAria: "打开 Codex Agent",
    composerCloseAria: "收起 Codex Agent",
    webPromptTitle: "生成提示词",
    webPromptIdle: "整理可移植的生成上下文",
    webPromptCopying: "正在复制",
    webPromptCopied: "已复制到剪贴板",
    copyPrompt: "复制提示词",
    openGenerator: "打开生成器",
    closeGenerator: "收起生成器",
    copyFailed: "无法复制提示词，请手动选择文本复制。",
    viewExamplePrompt: (name) => `查看 ${name} 示例提示词`,
    examplePromptRegion: (name) => `${name} 示例提示词`,
    flipToFront: "翻回作品正面",
    enlargeReference: (name) => `放大查看 ${name} 的参考图`,
    referenceAlt: (name) => `${name} 参考图`,
    closeReference: "关闭参考图",
    viewArtwork: (name) => `放大查看 ${name} 作品`,
    closeArtwork: "关闭作品大图",
    previousArtwork: "上一张作品",
    nextArtwork: "下一张作品",
    artworkPosition: (current, total) => `${current} / ${total}`,
    remix: "Remix",
    handoffRejected: "Codex 没有接收到这次 handoff",
    uploadUnsupported: "当前宿主不支持参考图上传",
    uploadFailed: "参考图上传失败",
    noGenerations: "还没有生成",
    noSkills: "没有可用 Skill",
    promptToImage: "提示词 → 成图",
    referenceToImage: "原图 → 成图",
    exportPromptToImage: "提示词 → 生成图",
    exportReferenceToImage: "原图 → 生成图",
    viewWork: (prompt, status) => `查看作品：${prompt}，${status}`,
    work: "作品",
    openItem: (label) => `打开 ${label}`,
    openItemWithMeta: (label, alt, meta) => `打开 ${label}：${alt}${meta ? `，${meta}` : ""}`,
    fanSummary: (label, total, expanded) => `${label}，${total} 件，${expanded ? "收起" : "展开"}`,
    status: {
      awaiting_agent: "等待 Codex",
      agent_running: "Codex 创作中",
      imagegen_running: "ImageGen 创作中",
      finalizing: "即将完成",
      succeeded: "完成",
      failed: "失败",
      cancelled: "已取消",
      unknown: "未完成",
    },
    validation: {
      skillUnavailable: "这个 Skill 当前不可用，请刷新或换一个。",
      emptyPrompt: "先写下你想生成的画面。",
      referencesUnsupported: "这个 Skill 不接受参考图。",
      tooManyReferences: (max) => `最多添加 ${max} 张参考图。`,
      unsupportedRatio: "这个 Skill 不支持所选比例。",
    },
    handoff: {
      intro: "你正在执行 Image Skill Studio 的一次图片生成任务。",
      contentHash: (hash) => `（内容哈希 ${hash}）`,
      creativeMethod: (id, skillPath, hashNote) =>
        `创作方法：\`$${id}\` Skill。先完整读取精确快照 ${skillPath}${hashNote}，严格遵循它的创作方法。`,
      renderGuidance:
        "出图优先使用 `$imagegen`（如果当前环境有）：按它的默认内置工具模式，用内置 image_gen 工具生成 1 张最终图片。不要使用 CLI（scripts/image_gen.py），不要要求 OPENAI_API_KEY。如果 `$imagegen` 不可用，或用户/环境里有更合适的其他生图 Skill、工具或手段，用那个即可。最终需要 1 张真实栅格图。",
      noReferences: "无参考图。",
      referenceItem: (index, location, role) => `${index}. ${location}（角色：${role}）`,
      runId: (id) => `Run ID：${id}`,
      scene: (prompt) => `画面要求：${prompt}`,
      ratio: (ratio) => `输出比例：${ratio}`,
      referencesHeading: "参考图：",
      recordSuccess: (tool, runId) =>
        `只有生成成功、并且已经有真实图片文件时，才调用本插件的 ${tool}，传入 runId "${runId}"、status "succeeded"；优先把生图工具返回的实际绝对路径作为 savedPath 传入，如果宿主只提供文件对象，则把产物作为 image 文件参数传入。生成失败时不要调用这个工具，不要记录失败。`,
      saveToDir: (dir) =>
        `把最终图片保存到目录 ${dir}。只把实际存在的绝对文件路径写入最终 JSON 的 artifactPaths；不可虚构路径。`,
      keepScope: "不要修改项目源代码，不要改写用户提示词。",
    },
  },
  en: {
    tryLuck: "Try your luck",
    tryLuckAria: "Open a random skill",
    creations: "Creations",
    skills: "Skills",
    settings: "Settings",
    appearance: "Appearance",
    themeLight: "Light",
    themeDark: "Dark",
    language: "Language",
    languageSystem: "System",
    languageChinese: "中文",
    languageEnglish: "English",
    openFullscreen: "Open fullscreen",
    registerSkill: "Register skill",
    refreshSkills: "Refresh skills",
    skillPath: "Absolute skill path",
    skillPathPlaceholder: "Absolute path to a skill folder or SKILL.md",
    overwriteRegistered: "Overwrite existing",
    registering: "Checking…",
    registerToStudio: "Register in Studio",
    fillSkillPath: "Enter the absolute path to a skill folder or SKILL.md.",
    registered: (name) => `Registered ${name}.`,
    installed: (destination) => `Installed to ${destination || "~/.codex/skills"}.`,
    backToFeed: "Back to Feed",
    skillContent: "Skill content",
    myGenerations: "My generations",
    installToCodex: "Install to Codex",
    overwriteInstall: "Overwrite install",
    generateSame: "Generate this",
    prompt: "Prompt",
    promptPlaceholder: "Describe the image you want…",
    addReference: "Add reference",
    referenceImage: "Reference image",
    removeReference: "Remove reference",
    writeAScene: "Write the scene you want to generate",
    handOff: "Hand off to Codex",
    handingOff: "Handing off…",
    composerReady: "Ready to create",
    composerHandedOff: "Handed off",
    composerOpenAria: "Open Codex agent",
    composerCloseAria: "Collapse Codex agent",
    webPromptTitle: "Generation prompt",
    webPromptIdle: "Portable context ready to copy",
    webPromptCopying: "Copying…",
    webPromptCopied: "Copied to clipboard",
    copyPrompt: "Copy prompt",
    openGenerator: "Open prompt generator",
    closeGenerator: "Collapse prompt generator",
    copyFailed: "Could not copy the prompt. Select the text and copy it manually.",
    viewExamplePrompt: (name) => `View the ${name} example prompt`,
    examplePromptRegion: (name) => `${name} example prompt`,
    flipToFront: "Flip back to the artwork",
    enlargeReference: (name) => `Enlarge the ${name} reference image`,
    referenceAlt: (name) => `${name} reference image`,
    closeReference: "Close reference image",
    viewArtwork: (name) => `Enlarge the ${name} artwork`,
    closeArtwork: "Close artwork viewer",
    previousArtwork: "Previous artwork",
    nextArtwork: "Next artwork",
    artworkPosition: (current, total) => `${current} / ${total}`,
    remix: "Remix",
    handoffRejected: "Codex did not accept this handoff",
    uploadUnsupported: "This host cannot upload reference images",
    uploadFailed: "Could not upload the reference image",
    noGenerations: "Nothing generated yet",
    noSkills: "No skills available",
    promptToImage: "Prompt → image",
    referenceToImage: "Reference → image",
    exportPromptToImage: "Prompt → generated image",
    exportReferenceToImage: "Reference → generated image",
    viewWork: (prompt, status) => `View work: ${prompt}, ${status}`,
    work: "Work",
    openItem: (label) => `Open ${label}`,
    openItemWithMeta: (label, alt, meta) => `Open ${label}: ${alt}${meta ? `, ${meta}` : ""}`,
    fanSummary: (label, total, expanded) => `${label}, ${total} pieces, ${expanded ? "collapse" : "expand"}`,
    status: {
      awaiting_agent: "Waiting for Codex",
      agent_running: "Codex is creating",
      imagegen_running: "ImageGen is creating",
      finalizing: "Finishing",
      succeeded: "Done",
      failed: "Failed",
      cancelled: "Cancelled",
      unknown: "Incomplete",
    },
    validation: {
      skillUnavailable: "This skill is unavailable. Refresh or pick another.",
      emptyPrompt: "Write the scene you want to generate.",
      referencesUnsupported: "This skill does not accept reference images.",
      tooManyReferences: (max) => `Add at most ${max} reference images.`,
      unsupportedRatio: "This skill does not support the selected ratio.",
    },
    handoff: {
      intro: "You are completing one Image Skill Studio image generation task.",
      contentHash: (hash) => ` (content hash ${hash})`,
      creativeMethod: (id, skillPath, hashNote) =>
        `Creative method: use the \`$${id}\` skill. Read the exact snapshot at ${skillPath}${hashNote} in full and follow it strictly.`,
      renderGuidance:
        "For the final image, prefer `$imagegen` when it is available: use its default built-in image_gen tool to make 1 raster image. Do not use the CLI (scripts/image_gen.py) and do not ask for OPENAI_API_KEY. If `$imagegen` is unavailable, or another image skill, tool, or method fits better, use that instead. Produce one real raster image.",
      noReferences: "None.",
      referenceItem: (index, location, role) => `${index}. ${location} (role: ${role})`,
      runId: (id) => `Run ID: ${id}`,
      scene: (prompt) => `Scene: ${prompt}`,
      ratio: (ratio) => `Output ratio: ${ratio}`,
      referencesHeading: "References:",
      recordSuccess: (tool, runId) =>
        `Only if generation succeeds and a real image file exists, call this plugin's ${tool} with runId "${runId}" and status "succeeded". Prefer the actual absolute path returned by the image tool as savedPath; if the host only provides a file object, pass the artifact as the image file parameter. If generation fails, do not call this tool and do not record a failure.`,
      saveToDir: (dir) =>
        `Save the final image to ${dir}. Write only real absolute file paths into artifactPaths in the final JSON; do not invent paths.`,
      keepScope: "Do not modify project source code. Do not rewrite the user's prompt.",
    },
  },
};

export function studioLanguage(locale) {
  const tag = String(locale || "").trim().toLowerCase();
  return tag.startsWith("zh") ? "zh" : "en";
}

export function studioCopy(locale) {
  return STUDIO_COPY[studioLanguage(locale)];
}

export function applyStudioLocale(locale, root = globalThis.document?.documentElement) {
  const language = studioLanguage(locale);
  if (root) {
    root.lang = language === "zh" ? "zh-CN" : "en";
    root.dataset.locale = language;
    root.dir = "ltr";
  }
  return language;
}
